### ISSUE TITLE
Hey, we got your information wrong

### ISSUE THREAD

**Issue by RALMAZ** [IvanSosnovich/JS-Profiles#1]
Greetings

![browser_rhj1KqAsr1](https://user-images.githubusercontent.com/26162860/93876970-5e1c2c80-fce0-11ea-9d2b-84e1b6ad6657.png)

How can we contact you 🤔 

msg me in tg `@RALMAZ`, if you still want to receive an invitation to W1 Academy

**Comment by IvanSosnovich** [comment]
I answer you, with telegram!

> 22 сент. 2020 г., в 14:35, Roman Almazov <notifications@github.com> написал(а):
> 
> @RALMAZ
